### PR TITLE
Option --vars for including JSON file with global variables

### PR DESCRIPTION
**Pull request by rutek**
Added `--vars path/to/env-vars.json` option so you can include global variables added to all included files. They may be overridden by file as they are added as they would exists in the beginning of file.

### CODE REVIEW

**Comment by gwillz** [comment]
Thanks for the PR! I really dig it.

I hadn't written this feature yet because I was thinking about how make sure it was compatible with the [environment variables in vscode-restclient](https://github.com/Huachao/vscode-restclient#environment-variables).

This PR is a pretty good start though - and it kind of justifies the class-based parser which I was always unsure of.

Do you mind if I riff on this PR and see what I can do?

**Comment by rutek** [comment]
I'm glad you like it. 😁 Feel free to modify it in any way, if it will end up in better functionality everybody will benefit from it.

**Comment by rutek** [comment]
One thought - I would consider if 100% compatibility with VS Code Rest Client environment variables is needed. If anyone uses it, he/she can execute request from VS Code. Maybe my view is not clear enough but to make things simpler: my personal goals is to:
- Give tool to other developers which doesn't use VS Code (especially JetBrains products - they have .http files support but it's not compatible with Rest Client).
- As I would have .http files in repository anyway: maybe run them during CI/CD just to make sure that everything is okay without spending time on creating Postman collections (better to have such simple test than none).

I was looking for such .http files tool and found your repository which just lacked these two functionalities to fulfill my needs so I decided to contribute to improve existing and somehow battle-tested tool as I think that .http files are great for small teams which would not like to pay $500/year to Postman for occasional use just to share HTTP requests inside team. It can be handled just by storing files in repository and using git-excluded variables (as it would contain credentials 😄).

**Comment by gwillz** [comment]
100% - you're preaching to the choir!

I found it much better (cheaper) to have all my API examples and testing requests as .http files in my version control. But like you, some of my colleagues don't use VSCode. Nor is it always best to fire up a whole editor to run a few tests or to populate a test environment.

**Comment by gwillz** [comment]
This is done in version 1.5.5!

You can use `--env` argument in two ways:
1. a path to a `.json` file - which works like your solution.
2. an 'environment' name, which refers to appropriate space in 'rest-client.environmentVariables' in the vscode settings.

The `$shared` space behaves as described in the plugin. No provided `--env` will use `$shared` variables. If there is a matched environment name, e.g. `--env production` then it will merge `$shared` and `production`.

It will look for the nearest `.vscode/settings.json` file. Failing that, it looks for a `package.json` file - this isn't standard rest-client. I'm not too fussed about it being different. It's just an extended interface that doesn't intefere with standard behaviour. It can be removed if it causes problems.

There's a bunch of stubs to fill out for additional rest-client settings like timeouts and default headers. I'll get to those eventually if someone else doesn't first.

Hope you like it!

**Pull request closed without merging**
